services:
  # Aplikasi Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-3000}:${APP_PORT:-3000}'
    env_file:
      - .env
    volumes:
      # Mount kode aplikasi untuk development (hot reload)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  # Redis untuk session cache
  redis:
    image: redis:latest
    container_name: nodejs-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
